In [2]:
import pandas as pd
from seeq import spy
import livef1

In [3]:
# Constants

# Workbook name will scope all the signals to a particular workbook, Change to None if you want them 
# globally soped and available in any workbook 

WORKBOOK_NAME = None
DATASOURCE_NAME = 'F1 Telemetry Playground'
SESSION_CONDITION_NAME = 'F1 Sessions'
CURRENT_SEASON = 2026

pd.options.display.max_columns = None

In [4]:
def add_capsule_start_end_session_df (df):
    df['session_startDate'] = pd.to_datetime(df['Session Startdate'])
    df['gmtoffset'] = pd.to_timedelta(df['Gmtoffset'])
    df['Capsule Start'] = (df['Session Startdate'] - df['gmtoffset'])
    df['Capsule End'] = (df['Session Enddate'] - df['gmtoffset'])
    df['Capsule Start'] = pd.to_datetime(df['Capsule Start'], utc=True)
    df['Capsule End'] = pd.to_datetime(df['Capsule End'], utc=True)
    return df

def set_signals_max_interpolation():
    scoped_workbook_id = None
    if WORKBOOK_NAME != None:
        scoped_workbook = spy.search({'Name':WORKBOOK_NAME, 'Type':'Workbook'})
        scoped_workbook_id = scoped_workbook['ID'][0]
    
    telemetry_signals = spy.search({'Name':'20??.*.*.*','Type':'Signal','Scoped To':scoped_workbook_id})
    metadata = telemetry_signals.copy()
    metadata['Maximum Interpolation'] = '5 min'
    # Push the updated metadata back to Seeq
    spy.push(metadata=metadata)
    


def get_session_data(current_time):
    """Fetch session data from Seeq."""
    scoped_workbook_id = None
    if WORKBOOK_NAME != None:
        scoped_workbook = spy.search({'Name':WORKBOOK_NAME, 'Type':'Workbook'})
        scoped_workbook_id = scoped_workbook['ID'][0]
        
    posted_session_condition = spy.search({'Name': SESSION_CONDITION_NAME, 'Datasource Name': DATASOURCE_NAME, 'Scoped To':scoped_workbook_id})
    posted_sessions = spy.pull(posted_session_condition, start='2023-01-01T00:00:00Z', end=current_time)
    return posted_sessions[posted_sessions['Capsule End'] < current_time]

def filter_sessions(sessions_df, posted_sessions):
    """Filter sessions that have not been processed yet."""
    return sessions_df[~sessions_df['Session Key'].isin(posted_sessions['Session Key'])]

def process_telemetry_data(telemetry_data, current_season, current_team_name, current_driver_no):
    """Process telemetry data for a specific driver."""
    telemetry_data = telemetry_data.dropna(subset=['DriverNo'])
    telemetry_data['DriverNo'] = pd.to_numeric(telemetry_data['DriverNo'], errors='coerce').astype('Int64')
    telemetry_data = telemetry_data.drop(columns=['SessionKey', 'DriverNo', 'timestamp','TrackRegion','TrackStatus'])
    telemetry_data['Utc'] = pd.to_datetime(telemetry_data['Utc'], utc=True)
    telemetry_data = telemetry_data.set_index('Utc')

    # Rename columns
    telemetry_data.columns = [
        f"{current_season}.{current_team_name}.{current_driver_no}.{col}" for col in telemetry_data.columns
    ]
    return telemetry_data

def process_laps_data(laps_data, current_team_name, current_driver_name, session_gmtoffset):
    """Process laps data for a specific driver."""
    laps_data = laps_data.dropna(subset=['LapTime'])
    laps_data['team_name'] = current_team_name
    laps_data['current_driver_name'] = current_driver_name
    laps_data['gmtoffset'] = pd.to_timedelta(session_gmtoffset)
    return laps_data

def create_sector_capsules(laps_data, sector_number):
    """Create sector capsules for a specific sector."""
    sector_caps = laps_data.copy()
    sector_caps['LapStartDate'] = pd.to_datetime(sector_caps['LapStartDate'], utc=True, errors='coerce')
    sector_caps['gmtoffset'] = pd.to_timedelta(sector_caps['gmtoffset'], errors='coerce').fillna(pd.Timedelta(0))
    sector_base_start = sector_caps['LapStartDate'] - sector_caps['gmtoffset']
    
    if sector_number == 1:
        sector_caps['Capsule Start'] = sector_base_start
        sector_caps['Capsule End'] = sector_caps['Capsule Start'] + sector_caps['Sector1_Time']
    if sector_number == 2:
        sector_caps['Capsule Start'] = sector_base_start + sector_caps['Sector1_Time']
        sector_caps['Capsule End'] = sector_caps['Capsule Start'] + sector_caps['Sector2_Time']
    if sector_number == 3:
        sector_caps['Capsule Start'] = sector_base_start + sector_caps['Sector1_Time'] + sector_caps['Sector2_Time']
        sector_caps['Capsule End'] = sector_caps['Capsule Start'] + sector_caps['Sector3_Time']
    
    sector_caps['Sector'] = sector_number
    sector_caps = sector_caps[['LapNo', 'DriverNo', 'Capsule Start', 'Capsule End', 'Sector', 'team_name', 'current_driver_name']]
    return sector_caps.dropna(subset=['Capsule Start', 'Capsule End'])

def push_telemetry_data(telemetry_data):
    """Push telemetry data to Seeq."""
    spy.push(data=telemetry_data, workbook=WORKBOOK_NAME, datasource=DATASOURCE_NAME)

def push_sector_data(all_sectors, current_season, current_team_name, current_driver_no):
    """Push sector data to Seeq."""
    metadata = pd.DataFrame([{
        'Name': f"{current_season}.{current_team_name}.{current_driver_no}.Sectors",
        'Type': 'Condition',
        'Maximum Duration': '5 min',
    }])
    spy.push(data=all_sectors, metadata=metadata, workbook=WORKBOOK_NAME, datasource=DATASOURCE_NAME)

def process_session(session, session_key, car_number_info, current_season, session_gmtoffset):
    """Process a single session."""
    laps_data = session.get_laps()
    laps_data = laps_data.dropna(subset = ['DriverNo'])
    laps_data['DriverNo'] = pd.to_numeric(laps_data['DriverNo'], errors='coerce').astype('Int64')
    
    telemetry_data = session.get_car_telemetry()
    telemetry_data = telemetry_data.dropna(subset = ['DriverNo'])
    telemetry_data['DriverNo'] = pd.to_numeric(telemetry_data['DriverNo'], errors='coerce').astype('Int64')

    cars_in_session = telemetry_data.DriverNo.unique()
    cars_pushed = 0

    for current_driver_no in cars_in_session:
        try:
            matching_row = car_number_info[
                (car_number_info['MinSessionKey'] <= session_key) &
                (car_number_info['MaxSessionKey'] >= session_key) &
                (car_number_info['DriverNo'] == current_driver_no)
            ]
    
            current_team_name = matching_row['TeamName'].values[0] if not matching_row.empty else None
            current_driver_name = matching_row['DriverName'].values[0] if not matching_row.empty else None
    
            # Process telemetry data
            driver_telemetry_data = process_telemetry_data(telemetry_data[telemetry_data.DriverNo == current_driver_no], current_season, current_team_name, current_driver_no)
            push_telemetry_data(driver_telemetry_data)
            print('Pushing Telemetry Data')
    
            # Process laps data
            driver_laps_data = process_laps_data(laps_data[laps_data.DriverNo == current_driver_no], current_team_name, current_driver_name, session_gmtoffset)
            print('Pushing Lap Data')
    
            # Create sector capsules
            sector_1_caps = create_sector_capsules(driver_laps_data, 1)
            sector_2_caps = create_sector_capsules(driver_laps_data, 2)
            sector_3_caps = create_sector_capsules(driver_laps_data, 3)
            print('Creating Sectors')
    
            all_sectors = pd.concat([sector_1_caps, sector_2_caps, sector_3_caps], ignore_index=True)
            push_sector_data(all_sectors, current_season, current_team_name, current_driver_no)
            print('Pushing Sectors')
    
            cars_pushed += 1
        except Exception as e:
            print(f"Skipping car {current_driver_no} due to error: {e}")
        continue

    return cars_pushed

In [5]:
"""Main function to process sessions."""
current_time = pd.Timestamp.now(tz='UTC')

# Load season and car information
season = livef1.get_season(CURRENT_SEASON)
season.parse_sessions()
sessions_df = season.season_table
car_number_info = pd.read_csv("data/CarTeamMap.csv")
sessions_df

,Season Year,Meeting Code,Meeting Number,Meeting Location,Meeting Offname,Meeting Name,Meeting Country Key,Meeting Country Code,Meeting Country Name,Meeting Circuit Key,Meeting Circuit Shortname,Session Key,Session Type,Session Name,Session Startdate,Session Enddate,Gmtoffset,Path
meeting_key,,,,,,,,,,,,,,,,,,
1304,2026,F12026T01,1,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,Pre-Season Testing,36,BRN,Bahrain,63,Sakhir,11465,Practice 1,Day 1,2026-02-11 10:00:00,2026-02-11 19:00:00,03:00:00,2026/2026-02-13_Pre-Season_Testing/2026-02-11_...
1304,2026,F12026T01,1,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,Pre-Season Testing,36,BRN,Bahrain,63,Sakhir,11466,Practice 2,Day 2,2026-02-12 10:00:00,2026-02-12 19:00:00,03:00:00,2026/2026-02-13_Pre-Season_Testing/2026-02-12_...
1304,2026,F12026T01,1,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,Pre-Season Testing,36,BRN,Bahrain,63,Sakhir,11467,Practice 3,Day 3,2026-02-13 10:00:00,2026-02-13 19:00:00,03:00:00,None

In [6]:
posted_sessions = get_session_data(current_time)
posted_sessions

SPy Error: No datasource found that matches "F1 Telemetry Playground"

Error found at line 31 in cell 4.

Button(description='Click to show stack trace', layout=Layout(height='auto', width='auto'), style=ButtonStyle(…

In [7]:
try:
    posted_sessions = get_session_data(current_time)
    filtered_sessions = filter_sessions(sessions_df, posted_sessions)

except Exception as e:
    print(f"No prior sessions have been uploaded posting all sessions - error text: {e}")
    filtered_sessions = sessions_df
    posted_sessions = None

filtered_sessions = add_capsule_start_end_session_df(filtered_sessions)
filtered_sessions

No prior sessions have been uploaded posting all sessions - error text: No datasource found that matches "F1 Telemetry Playground"

,Season Year,Meeting Code,Meeting Number,Meeting Location,Meeting Offname,Meeting Name,Meeting Country Key,Meeting Country Code,Meeting Country Name,Meeting Circuit Key,Meeting Circuit Shortname,Session Key,Session Type,Session Name,Session Startdate,Session Enddate,Gmtoffset,Path,session_startDate,gmtoffset,Capsule Start,Capsule End
meeting_key,,,,,,,,,,,,,,,,,,,,,,
1304,2026,F12026T01,1,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,Pre-Season Testing,36,BRN,Bahrain,63,Sakhir,11465,Practice 1,Day 1,2026-02-11 10:00:00,2026-02-11 19:00:00,03:00:00,2026/2026-02-13_Pre-Season_Testing/2026-02-11_...,2026-02-11 10:00:00,0 days 03:00:00,2026-02-11 07:00:00+00:00,2026-02-11 16:00:00+00:00
1304,2026,F12026T01,1,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,Pre-Season Testing,36,BRN,Bahrain,63,Sakhir,11466,Practice 2,Day 2,2026-02-12 10:00:00,2026-02-12 19:00:00,03:00:00,2026/2026-02-13_Pre-Season_Testing/2026-02-12_...,2026-02-12 10:00:00,0 days 03:00:00,2026-02-12 07:00:00+00:00,2026-02-12 16:00:00+00:00
1304,2026,F12026T01,1,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,Pre-Season Testing,36,BRN,Bahrain,63,Sakhir,11467,Practice 3,Day 3,2026-02-13 10:00:00,2026-02-13 19:00:00,03:00:00,None,2026-02-13 10:00:00,0 days 03:00:00,2026-02-13 07:00:00+00:00,2026-02-13 16:00:00+00:00

In [8]:
for index, row in filtered_sessions.iterrows():
    current_session_key = row['Session Key']
    session = livef1.get_session(season=CURRENT_SEASON, meeting_key=index, session_key=current_session_key)
    session_generated = False
    try:
        session.generate(silver=True)
        session_generated = True
    except Exception as e:
        print(f"Skipping session {row['session_key']} due to error: {e}")
        continue
        
    if session_generated:
        
        cars_pushed = process_session(session, current_session_key, car_number_info, CURRENT_SEASON, row['Gmtoffset'])

        if cars_pushed > 0:
            # Push session metadata

            keep_cols = [
                "Capsule Start", 
                "Capsule End",
                "index", 
                "Season Year",
                "Meeting Location",
                "Meeting Offname",
                "Meeting Name",
                "Meeting Country Name",
                "Meeting Circuit Shortname",
                "Session Key",
                "Session Type",
                "Session Name"]
            
            session_capsule = pd.DataFrame([row]).reset_index()
            session_capsule = session_capsule[keep_cols]
            session_capsule = session_capsule.rename(columns={'index': 'Meeting Key'})
            
            spy.push(data=session_capsule, metadata=pd.DataFrame([{
                'Name': SESSION_CONDITION_NAME,
                'Type': 'Condition',
                'Maximum Duration': '7d',
            }]), workbook=WORKBOOK_NAME, datasource=DATASOURCE_NAME)

00:26:39 - Selected meeting/session is:
	Meeting Offname : FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026
	Meeting Name : Pre-Season Testing
	Meeting Circuit Shortname : Sakhir
00:26:39 - Got the meeting.
00:26:39 - Selected meeting/session is:
	session_name : Day 3
00:26:39 - The session was received successfully.

AttributeError: 'Session' object has no attribute 'full_path'

Error found at line 3 in cell 8.

Button(description='Click to show stack trace', layout=Layout(height='auto', width='auto'), style=ButtonStyle(…

In [ ]:
spy.jobs.schedule('0 0 0-23 ? * FRI,SAT,SUN *')