In [1]:
import pandas as pd
from seeq import spy
from seeq.spy.assets import Asset, ItemGroup
pd.options.display.max_columns = None

In [2]:
WORKBOOK_NAME = None
DATASOURCE_NAME = 'F1 Telemetry Playground'
SESSION_CONDITION_NAME = 'F1 Sessions'

In [3]:
scoped_workbook_id = None
if WORKBOOK_NAME != None:
    scoped_workbook = spy.search({'Name':WORKBOOK_NAME, 'Type':'Workbook'})
    scoped_workbook_id = scoped_workbook['ID'][0]

sessions_condition = spy.search({'Name':'F1 Sessions','Datasource Name':DATASOURCE_NAME, 'Scoped To':scoped_workbook_id, 'Type':['Condition']})
sessions_condition_id= sessions_condition['ID'][0]
sessions_condition_id

'0F108719-5EFB-FF80-A151-4FB8CFCED7D6'

In [4]:
def get_f1_items():
    scoped_workbook_id = None
    if WORKBOOK_NAME != None:
        scoped_workbook = spy.search({'Name':WORKBOOK_NAME, 'Type':'Workbook'})
        scoped_workbook_id = scoped_workbook['ID'][0]
    
    telemetry_items = spy.search({'Name':'????.*','Datasource Name':DATASOURCE_NAME, 'Scoped To':scoped_workbook_id, 'Type':['Signal','Condition']})
    
    return telemetry_items

In [5]:
class F1_Car(Asset):

    @Asset.Attribute()
    def TrackSectors(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Sectors')]
        condition_id = row.iloc[0]['ID']
        if row.empty:
            return None
        return {'Type': 'Condition',
                'Formula': "$condition",
                'Formula Parameters': {'$condition': condition_id}}

    @Asset.Attribute()
    def X_pos(self, metadata):
        row = metadata[metadata['Name'].str.endswith('X')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Y_pos(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Y')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Z_pos(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Z')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def RPM(self, metadata):
        row = metadata[metadata['Name'].str.endswith('RPM')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Throttle(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Throttle')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Brake(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Brake')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Gear(self, metadata):
        row = metadata[metadata['Name'].str.endswith('GearNo')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min).tostep()",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Speed(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Speed')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def LapNumber(self, metadata):
        row = metadata[metadata['Name'].str.endswith('LapNo')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min).tostep()",
            'Formula Parameters': {'$signal': signal_id}
        }


    @Asset.Attribute()
    def CarStatus(self, metadata):
        row = metadata[metadata['Name'].str.endswith('CarStatus')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def TrackStatus(self, metadata):
        row = metadata[metadata['Name'].str.endswith('TrackStatus')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Compound(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Compound')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def Distance(self, metadata):
        row = metadata[metadata['Name'].str.endswith('Distance')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min)",
            'Formula Parameters': {'$signal': signal_id}
        }

    @Asset.Attribute()
    def TireAge(self, metadata):
        row = metadata[metadata['Name'].str.endswith('TyreAge')]
        if row.empty:
            return None
        signal_id = row.iloc[0]['ID']
        return {
            'Type': 'Signal',
            'Formula': "$signal.setMaxInterpolation(2min).tostep()",
            'Formula Parameters': {'$signal': signal_id}
        }

    #####  Calculations

    @Asset.Attribute()
    def Laps(self, metadata):
        lap_number = self.LapNumber(metadata)
        if lap_number is None:
            return None
    
        speed_signal = self.Speed(metadata)
        if speed_signal is None:
            return None
    
        tire = self.Compound(metadata)
        if tire is None:
            return None

    
        # Extract car number and team name from metadata
        car_number = metadata['Car Number'].iloc[0]
        team_name = metadata['Team'].iloc[0]
    
        session_condition = sessions_condition_id
        return {
            'Type': 'Condition',
            'Formula': f"""
                $lap_no.toCondition().removeLongerThan(6h)
                .renameProperty('value','lap number')
                .mergeProperties($session.removeLongerThan(1d))
                .setProperty('Max Speed',$spd , maxValue())
                .setProperty('Tire Compound',$tire,startValue())
                .setProperty('Car Number', '{car_number}')
                .setProperty('Team', '{team_name}')
            """,
            'Formula Parameters': {
                '$lap_no': lap_number,
                '$session': session_condition,
                '$spd': speed_signal,
                '$tire': tire,
            }
        }

    @Asset.Attribute()
    def Sector_1(self, metadata):
        sectors = self.TrackSectors(metadata)
        if sectors is None:
            return None
        return {
            'Type': 'Condition',
            'Formula': "$condition.keep('Sector', isEqualTo(1))",
            'Formula Parameters': {'$condition': sectors}
        }

    @Asset.Attribute()
    def Sector_2(self, metadata):
        sectors = self.TrackSectors(metadata)
        if sectors is None:
            return None
        return {
            'Type': 'Condition',
            'Formula': "$condition.keep('Sector', isEqualTo(2))",
            'Formula Parameters': {'$condition': sectors}
        }

    @Asset.Attribute()
    def Sector_3(self, metadata):
        sectors = self.TrackSectors(metadata)
        if sectors is None:
            return None
        return {
            'Type': 'Condition',
            'Formula': "$condition.keep('Sector', isEqualTo(3))",
            'Formula Parameters': {'$condition': sectors}
        }

In [6]:
telemetry_items = get_f1_items()
telemetry_items = telemetry_items[telemetry_items['Datasource Name']=='F1 Telemetry Playground']
telemetry_items[['Season', 'Team', 'Car Number', 'Tag Name']] = telemetry_items['Name'].str.split('.', expand=True)
telemetry_items['Build Asset'] = telemetry_items['Car Number'] 
telemetry_items ['Build Path'] = 'F1 Telemetry >> ' + telemetry_items['Season'] + ' >> ' + telemetry_items['Team']
telemetry_items

,ID,Name,Description,Type,Value Unit Of Measure,Datasource Name,Archived,Season,Team,Car Number,Tag Name,Build Asset,Build Path
0,0F10870D-F9FB-60A0-97B0-FCE331579DB2,2026.Alpine.10.Sectors,NaN,StoredCondition,NaN,F1 Telemetry Playground,False,2026,Alpine,10,Sectors,10,F1 Telemetry >> 2026 >> Alpine
1,0F108716-612A-62A0-9C68-B580EC013CE5,2026.Alpine.43.Sectors,NaN,StoredCondition,NaN,F1 Telemetry Playground,False,2026,Alpine,43,Sectors,43,F1 Telemetry >> 2026 >> Alpine
2,0F108720-5825-EEC0-9ADC-CC7E5DFA401A,2026.Aston Martin.14.Sectors,NaN,StoredCondition,NaN,F1 Telemetry Playground,False,2026,Aston Martin,14,Sectors,14,F1 Telemetry >> 2026 >> Aston Martin
3,0F108711-7FD7-E810-BA3B-DAA0FB318C9B,2026.Aston Martin.18.Sectors,NaN,StoredCondition,NaN,F1 Telemetry Playground,False,2026,Aston Martin,18,Sectors,18,F1 Telemetry >> 2026 >> Aston Martin
4,0F108713-673A-6030-B1E4-6458B9B5DC92,2026.Audi.27.Sectors,NaN,StoredCondition,NaN,F1 Telemetry Playground,False,2026,Audi,27,Sectors,27,F1 Telemetry >> 2026 >> Audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,0F108717-AC2F-6600-A1D4-290222639A1C,2026.Williams.55.TyreAge,NaN,StoredSignal,NaN,F1 Telemetry Playground,False,2026,Williams,55,TyreAge,55,F1 Telemetry >> 2026 >> Williams
348,0F108717-69E2-FB80-866F-02F2B0686AD6,2026.Williams.55.X,NaN,StoredSignal,NaN,F1 Telemetry Playground,False,2026,Williams,55,X,55,F1 Telemetry >> 2026 >> Williams
349,0F108717-9CBC-64C0-A88D-31DA76B1D29B,2026.Williams.55.Y,NaN,StoredSignal,NaN,F1 Telemetry Playground,False,2026,Williams,55,Y,55,F1 Telemetry >> 2026 >> Williams
350,0F108717-A0EC-7130-B9C5-E89AD05E9AE4,2026.Williams.55.Z,NaN,StoredSignal,NaN,F1 Telemetry Playground,False,2026,Williams,55,Z,55,F1 Telemetry >> 2026 >> Williams
351,0F108717-B7C0-ECD0-AA51-A0FB222AA0FC,2026.Williams.55.tag,NaN,StoredSignal,string,F1 Telemetry Playground,False,2026,Williams,55,tag,55,F1 Telemetry >> 2026 >> Williams

In [7]:
build_df = spy.assets.build(F1_Car, telemetry_items)
build_df['Maximum Interpolation'] = '15 min'
build_df.to_csv('build.csv')
build_df['Maximum Duration'] = '12h'
build_df[:30]

,Type,Formula,Formula Parameters,Name,Asset,Asset Object,Path,Template,Build Result,Maximum Interpolation,Maximum Duration
0,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-0EA2-6040-8B76-1B4D57B51...,Brake,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
1,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-99FE-6490-BCCE-80BD3B010...,CarStatus,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
2,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-9451-EA60-B39C-CE16E6214...,Compound,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
3,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-96BB-7530-B53C-C0F4470C9...,Distance,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
4,Signal,$signal.setMaxInterpolation(2min).tostep(),{'$signal': '0F10870D-0E47-EAF0-B28F-A78EBA577...,Gear,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
5,Signal,$signal.setMaxInterpolation(2min).tostep(),{'$signal': '0F10870D-0B55-64A0-8E39-7DD305485...,LapNumber,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
6,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-0B66-6610-8600-0585CA7AC...,Speed,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
7,Condition,$lap_no.toCondition().removeLongerThan(6h)\n.r...,"{'$lap_no': {'Type': 'Signal', 'Formula': '$si...",Laps,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
8,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-0B61-77F0-BAA2-CE1E15E3D...,RPM,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
9,Condition,$condition,{'$condition': '0F10870D-F9FB-60A0-97B0-FCE331...,TrackSectors,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
10,Condition,"$condition.keep('Sector', isEqualTo(1))","{'$condition': {'Type': 'Condition', 'Formula'...",Sector 1,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
11,Condition,"$condition.keep('Sector', isEqualTo(2))","{'$condition': {'Type': 'Condition', 'Formula'...",Sector 2,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
12,Condition,"$condition.keep('Sector', isEqualTo(3))","{'$condition': {'Type': 'Condition', 'Formula'...",Sector 3,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
13,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-0EBC-FDF0-A0C2-CE6B82DD8...,Throttle,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
14,Signal,$signal.setMaxInterpolation(2min).tostep(),{'$signal': '0F10870D-95CE-E820-864C-22FEF859B...,TireAge,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
15,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-0F9D-77B0-9BF9-D37739FB0...,X pos,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
16,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-7B79-EC90-A0C8-0DFA8FF2A...,Y pos,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
17,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F10870D-83F1-EC10-A6A7-C89733554...,Z pos,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
18,Asset,NaN,NaN,10,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
19,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F108716-0865-E8E0-BF81-8028ED093...,Brake,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
20,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F108716-4032-7390-94E2-A577062E8...,CarStatus,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
21,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F108716-34BE-7180-8FDE-CF96689A1...,Compound,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
22,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F108716-40B3-F9E0-BEF0-F5EBFFD42...,Distance,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
23,Signal,$signal.setMaxInterpolation(2min).tostep(),{'$signal': '0F108716-07B8-7370-94ED-8084BFDBE...,Gear,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
24,Signal,$signal.setMaxInterpolation(2min).tostep(),{'$signal': '0F108716-06E8-FB20-AABB-8E9258777...,LapNumber,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
25,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F108716-0723-64A0-901B-7E8F0589F...,Speed,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
26,Condition,$lap_no.toCondition().removeLongerThan(6h)\n.r...,"{'$lap_no': {'Type': 'Signal', 'Formula': '$si...",Laps,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
27,Signal,$signal.setMaxInterpolation(2min),{'$signal': '0F108716-072F-77F0-817F-05A68EE36...,RPM,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
28,Condition,$condition,{'$condition': '0F108716-612A-62A0-9C68-B580EC...,TrackSectors,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h
29,Condition,"$condition.keep('Sector', isEqualTo(1))","{'$condition': {'Type': 'Condition', 'Formula'...",Sector 1,43,F1 Telemetry >> 2026 >> Alpine >> 43,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h

In [8]:
spy.push(metadata=build_df, workbook=WORKBOOK_NAME)

,Type,Formula,Formula Parameters,Name,Asset,Asset Object,Path,Template,Build Result,Maximum Interpolation,Maximum Duration,Scoped To,Datasource Class,Datasource ID,Data ID,ID,Push Result,Cache Enabled,Push Method
0,CalculatedSignal,$signal.setMaxInterpolation(2min),[signal=0F10870D-0EA2-6040-8B76-1B4D57B51B99],Brake,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Signal...,0F108732-2997-66A0-9AAC-0DAE67497C9A,Success,NaN,NaN
1,CalculatedSignal,$signal.setMaxInterpolation(2min),[signal=0F10870D-99FE-6490-BCCE-80BD3B0101FD],CarStatus,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Signal...,0F108732-29CF-F910-920B-0C0E4F7289D2,Success,NaN,NaN
2,CalculatedSignal,$signal.setMaxInterpolation(2min),[signal=0F10870D-9451-EA60-B39C-CE16E6214DFA],Compound,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Signal...,0F108732-29DE-7370-9E08-54F3CAA06558,Success,NaN,NaN
3,CalculatedSignal,$signal.setMaxInterpolation(2min),[signal=0F10870D-96BB-7530-B53C-C0F4470C9096],Distance,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Signal...,0F108732-29EA-66C0-9C25-41FFDDB46810,Success,NaN,NaN
4,CalculatedSignal,$signal.setMaxInterpolation(2min).tostep(),[signal=0F10870D-0E47-EAF0-B28F-A78EBA577977],Gear,10,F1 Telemetry >> 2026 >> Alpine >> 10,F1 Telemetry >> 2026 >> Alpine,F1 Car,Success,15 min,12h,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Signal...,0F108732-29F6-EA10-A8FD-C11011E60BE7,Success,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
__side_effect_asset_9__,Asset,NaN,NaN,McLaren,McLaren,NaN,F1 Telemetry >> 2026,NaN,NaN,NaN,NaN,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Asset}...,0F108732-365E-EE60-8B94-82AF61F320F9,Success,NaN,batch
__side_effect_asset_10__,Asset,NaN,NaN,Mercedes,Mercedes,NaN,F1 Telemetry >> 2026,NaN,NaN,NaN,NaN,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Asset}...,0F108732-365E-EE60-9341-E7ABD81951AE,Success,NaN,batch
__side_effect_asset_11__,Asset,NaN,NaN,Racing Bulls,Racing Bulls,NaN,F1 Telemetry >> 2026,NaN,NaN,NaN,NaN,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Asset}...,0F108732-365E-EE60-9447-9BEAA9371ECB,Success,NaN,batch
__side_effect_asset_12__,Asset,NaN,NaN,Red Bull Racing,Red Bull Racing,NaN,F1 Telemetry >> 2026,NaN,NaN,NaN,NaN,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Asset}...,0F108732-365E-EE60-B820-60C2E6757657,Success,NaN,batch
__side_effect_asset_13__,Asset,NaN,NaN,Williams,Williams,NaN,F1 Telemetry >> 2026,NaN,NaN,NaN,NaN,NaN,Seeq Data Lab,Seeq Data Lab,[00000000-0000-0000-0000-000000000000] {Asset}...,0F108732-3661-7570-A3E6-62BAC2FE057B,Success,NaN,batch